language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "pypy"
env:
    - DJANGO="django>=1.8,<1.9"
    - DJANGO="django>=1.9"
install:
    - "pip install -r ci_requirements.txt --use-mirrors"
    - "pip install ${DJANGO}"
before_script:
    - "pip install python-coveralls coverage"
script:
    - "coverage run runtests.py"
after_success:
    - "coveralls"
notifications:
    email: false
